name: LargeRepo

on: [ pull_request ]

env:
  NX_BRANCH: ${{ github.event.number || github.ref }}
  NX_RUN_GROUP: ${{ github.run_id }}
  NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'

jobs:
  agents:
    name: Nx Cloud Agents
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent

  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
      - run: npm install
      - name: Run verification
        uses: JamesHenry/parallel-bash-commands@v0.1
        with:
          cmd1: npx nx affected --base=HEAD~1 --target=build --parallel --max-parallel=3
          cmd2: npx nx affected --base=HEAD~1 --target=test --parallel --max-parallel=3
          cmd3: npx nx affected --base=HEAD~1 --target=lint --parallel --max-parallel=3
          cmd4: npx nx affected --base=HEAD~1 --target=e2e
      - run: npx nx-cloud stop-all-agents

  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v1
      - run: npm install
      - name: Run verification
        uses: JamesHenry/parallel-bash-commands@v0.1
        with:
          cmd1: npx nx affected --base=origin/main --target=build --parallel --max-parallel=3
          cmd2: npx nx affected --base=origin/main --target=test --parallel --max-parallel=3
          cmd3: npx nx affected --base=origin/main --target=lint --parallel --max-parallel=3
          cmd4: npx nx affected --base=origin/main --target=e2e
      - run: npx nx-cloud stop-all-agents
